services:
  renovate:
    image: renovate/renovate:latest
    container_name: renovate
    environment:
      - RENOVATE_PLATFORM=github
      - RENOVATE_TOKEN=${RENOVATE_TOKEN}
      - RENOVATE_CONFIG_FILE=/usr/src/app/config.js
#      - LOG_LEVEL=debug
    volumes:
      - ./config.js:/usr/src/app/config.js:ro
      - renovate-cache:/tmp/renovate
        
volumes:
  renovate-cache: